---
- name: reset_azure_cni
  command: /bin/true
  notify:
    - delete 10-azure.conflist

- name: delete 10-calico.conflist
  file:
    path: /etc/cni/net.d/10-azure.conflist
    state: absent

- name: Azure | Reload NetworkManager
  service:
    name: NetworkManager
    state: reloaded
  when: '"running" in nm_check.stdout'
